import { StyleSheet } from "react-native";

import {
  colors,
  textShadow,
  borderRadius,
  padding,
  margin,
} from "../../constants/constants";
const styles = {
  cell: {
    flexGrow: 1,
    aspectRatio: 1,
    margin,
    justifyContent: "center",
    alignItems: "center",
  },
};

export default StyleSheet.create({
  mainContainer: { backgroundColor: colors.secondary, flex: 1, padding: 24 },
  gridContainer: {
    padding,
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius,
    borderColor: colors.black,
    borderWidth: 1,
  },
  userColumn: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexBasis: "7%",
    flexGrow: 1,
  },
  hourColumn: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    flexBasis: "11%",
    flexGrow: 1,
  },
  leftbufferCell: {
    ...styles.cell,
    margin,
    fontSize: 30,
  },
  lefthourCell: {
    ...styles.cell,
    fontSize: 30,
    margin,
    color: colors.white,
    textAlign: "center",
    ...textShadow,
  },
  hourCell: {
    ...styles.cell,
    borderColor: colors.black,
    borderWidth: 1,
    color: colors.white,
    textAlign: "center",
    borderRadius,
  },
  userName: {
    ...styles.cell,
    flexBasis: "5.5%",
    margin: 4,
    flexGrow: 1,
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    fontSize: 30,
    color: colors.white,
    borderColor: "black",
    height: 40, // Add a fixed height
    width: 40, // Add a fixed width
  },
  green: { backgroundColor: colors.green },
  yellow: { backgroundColor: colors.yellow },
  red: { backgroundColor: colors.red },
  highlighted: {
    backgroundColor: colors.green,
    borderWidth: 2,
    borderColor: colors.black,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding,
  },
  button: { backgroundColor: colors.blue, padding, borderRadius },
  userImage: {
    flexBasis: "4%",
    flexGrow: 1,
    margin,
    borderRadius: 50,
    aspectRatio: 1,
    borderWidth: 2,
    fontSize: 30,
    borderColor: "black",
    backgroundColor: "#333333",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "cover",
  },
  buttonTextStyle: {
    color: "white",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  userImagePlaceholder: {
    flexBasis: "10%",
    flexGrow: 1,
    margin,
    borderRadius: 50,
    aspectRatio: 1,
    borderWidth: 2,
    fontSize: 30,
    borderColor: "black",
    backgroundColor: "#333333",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "cover",
  },
});
