import { StyleSheet } from "react-native";

export default StyleSheet.create({
  mainContainer: {
    backgroundColor: "#2C3F50",
    flex: 1,
    padding: 24,
  },
  header: {
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#3C4C6C",
    borderRadius: 20,
    marginTop: 20,
    borderColor: "#000000",
    borderWidth: 1,
  },
  arrowButton: {
    padding: 12,
    borderRadius: 8,
  },
  arrowText: {
    fontSize: 24,
    color: "#FFFFFF",
  },
  dateText: {
    fontSize: 24,
    color: "#FFFFFF",
    paddingHorizontal: 16,
  },
  summaryContainer: {
    padding: 24,
    borderRadius: 8,
    marginBottom: 16,
  },
  textInput: {
    height: "auto",
    borderColor: "#000000",
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
    fontSize: 18,
    color: "white",
    textAlign: "center",
    backgroundColor: "#3C4C6C",
    borderRadius: 8,
    marginTop: 10,
  },
  gridContainer: {
    padding: 24,
    flex: 1,
    backgroundColor: "#3C4C6C",
    borderRadius: 8,
    borderColor: "#000000",
    borderWidth: 1,
  },
  userColumn: {
    flexDirection: "row",
    marginBottom: 16,
    marginLeft: 45,
  },
  hourColumn: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  hourCell: {
    width: 40,
    height: 40,
    margin: 4,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "black",
    borderWidth: 1,
    fontSize: 18,
    color: "white",
    textAlign: "center",
    borderRadius: 8,
  },
  userName: {
    width: 40,
    margin: 4,
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 18,
    color: "white",
  },
  green: {
    backgroundColor: "#2ECC71",
  },
  yellow: {
    backgroundColor: "#FFF000",
  },
  red: {
    backgroundColor: "#E74C3C",
  },
  highlighted: {
    backgroundColor: "#2ECC71",
    borderWidth: 2,
    borderColor: "black",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 24,
  },
  button: {
    backgroundColor: "#3498DB",
    padding: 16,
    borderRadius: 8,
  },
  userImage: {
    width: 40,
    height: 40,
    margin: 4,
  },
});
